name: Cache CI

on:
  push:
    paths:
      - 'hw1_Cache/**'
      - '.github/workflows/cache-ci.yml'
  pull_request:
    paths:
      - 'hw1_Cache/**'
      - '.github/workflows/cache-ci.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    container:
      image: isshlyapin/ubuntu_cpp:cxx23

    strategy:
      matrix:
        build_type: [Debug, Release]

    defaults:
      run:
        working-directory: hw1_Cache

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Conan
        run: |
          conan config install https://github.com/isshlyapin/conan_config.git
          conan build . --build=missing -s build_type=${{ matrix.build_type }} -pr:a clang21 -o btest=True

      - name: Run tests
        run: |
          ctest --test-dir build/${{ matrix.build_type }}/tests --output-on-failure --timeout 15
