name: Matrix CI

on:
  push:
    paths:
      - 'hw4_Matrix/**'
      - '.github/workflows/matrix-ci.yml'
  pull_request:
    paths:
      - 'hw4_Matrix/**'
      - '.github/workflows/matrix-ci.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    container:
      image: isshlyapin/ubuntu_cpp:cxx23

    defaults:
      run:
        working-directory: hw4_Matrix

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Conan
        run: |
          conan config install https://github.com/isshlyapin/conan_config.git
          conan build . --build=missing -s build_type=Release -pr:a clang21 -o btest_opt=True

      - name: Run tests
        run: |
          ctest --test-dir build/Release/test --output-on-failure --timeout 3

      - name: Run E2E tests
        run: |
          uv run pytest script/test_det_e2e.py -v
