name: Tree CI

on:
  push:
    paths:
      - 'hw3_Tree/**'
      - '.github/workflows/tree-ci.yml'
  pull_request:
    paths:
      - 'hw3_Tree/**'
      - '.github/workflows/tree-ci.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    container:
      image: isshlyapin/ubuntu_cpp:cxx23

    defaults:
      run:
        working-directory: hw3_Tree

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Conan
        run: |
          conan config install https://github.com/isshlyapin/conan_config.git
          conan build . --build=missing -s build_type=Debug -pr:a clang21 -o btest=True

      - name: Run tests
        run: |
          ctest --test-dir build/Debug/test --output-on-failure --timeout 3
